[System.Environment]::SetEnvironmentVariable(
    "XDG_CACHE_HOME",
    "%TEMP%",
    [System.EnvironmentVariableTarget]::User
)
[System.Environment]::SetEnvironmentVariable(
    "XDG_STATE_HOME",
    "%LOCALAPPDATA%",
    [System.EnvironmentVariableTarget]::User
)
[System.Environment]::SetEnvironmentVariable(
    "XDG_DATA_HOME",
    "%APPDATA%",
    [System.EnvironmentVariableTarget]::User
)
[System.Environment]::SetEnvironmentVariable(
    "XDG_CONFIG_HOME",
    "%USERPROFILE%\Document",
    [System.EnvironmentVariableTarget]::User
)
