let s:denops = expand("~/.cache/vim/denotest/github.com/vim-denops/denops.vim")
if !isdirectory(s:denops)
  execute 'silent! !git clone https://github.com/vim-denops/denops.vim ' .. s:denops
endif
execute 'set runtimepath^=' . substitute(fnamemodify(s:denops, ':p') , '[/\\]$', '', '')

augroup MyDenopsConfig
  autocmd!
  " denopsがロードされた直後のコール
  autocmd User DenopsReady echomsg "Denops is ready!"
  " プラグインがロードされた直後のコール
  autocmd User DenopsPluginPost:test call denops#request('test', 'stst', [])
augroup END

let g:denops#debug = 1
