" let s:denops = expand("~/.cache/vim/denotest/github.com/vim-denops/denops.vim")
" if !isdirectory(s:denops)
"   execute 'silent! !git clone https://github.com/vim-denops/denops.vim ' .. s:denops
" endif
" execute 'set runtimepath^=' . substitute(fnamemodify(s:denops, ':p') , '[/\\]$', '', '')

" augroup MyDenopsConfig
"   autocmd!
"   " denopsがロードされた直後のコール
"   autocmd User DenopsReady echomsg "Denops is ready!"
"   " プラグインがロードされた直後のコール
"   autocmd User DenopsPluginPost:test call denops#request('test', 'stst', [])
"   autocmd User DenopsPluginPost:gamen if argc() == 0 | call denops#request("gamen", "gamensetup", []) | endif
" augroup END

let g:denops#debug = 1
set runtimepath+=~/.cache/vim/denotest/github.com/vim-denops/denops-shared-server.vim
let g:denops_server_addr = "127.0.0.1:34141"

" set runtimepath+=~/.cache/vim/denotest/github.com/edgwitr/petit.vim
" call petit#setup()
" call petit#pairs#setup()

" set runtimepath+=~/.cache/vim/denotest/github.com/edgwitr/petit.treesitter
" call petit#treesitter#setup({
      \ 'highlight': {
        \ "enable": v:true,
        \ "disable": ["cpp"],
      \ },
      \ 'ensure_installed': ["c"]
      \ })

" set runtimepath+=~/.cache/vim/denotest/github.com/edgwitr/petit.lsp
